server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/trazabilidad
      database: trazabilidad

appDescription: "Pragma Powerup"
appVersion: "1.0.0"

external:
  ms-users: "http://localhost:8081"

security:
  jwt-key: ea69c58750cbe6d90fedff638d48938a8b9165e0a59278b77e7754e0a6b00031
  jwt-user-generator: AUTH0JWT